
version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    # freshness:
    #   error_after:
    #     count: 12
    #     period: hour
    #   loaded_at_field: created_at
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
 
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: customers
    description: "Cleaned up data for our coffee shop customers"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: monthly_customers
    description: "Count of new customers by month"
    columns:
      - name: signup_month
        description: "The primary key for this table"
        tests:
          - unique
          - not_null


# run tests on all sources
# dbt test --select source:*

# run test on one model
# dbt run --select monthly_customers